INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (2, '2019-11-25 16:14:07', NULL, NULL, NULL, NULL, 'BMG');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (3, '2019-11-25 16:37:49', NULL, NULL, NULL, NULL, 'BUMA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (4, '2019-11-25 16:37:54', NULL, NULL, NULL, NULL, 'CMRRA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (5, '2019-11-25 16:38:16', NULL, NULL, NULL, NULL, 'Concord');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (6, '2019-11-25 16:38:39', NULL, NULL, NULL, NULL, 'Eleven Seven Mechanicals');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (7, '2019-11-25 17:01:59', NULL, NULL, NULL, NULL, 'HFA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (8, '2019-11-25 17:02:24', NULL, NULL, NULL, NULL, 'Legacy Mechanicals');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (10, '2020-01-13 15:58:30', NULL, NULL, NULL, NULL,'MILAN');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (11, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'MRI');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (12, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'Spotify');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (14, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'SESAC');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (15, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'SME Mechanicals');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (16, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'SOCAN');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (17, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'Sony');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (18, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'STATE51');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (19, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'STEMRA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (20, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'STIM');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (21, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'Face the Wind/Iyeoka');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (27, '2020-01-21 23:28:42', NULL, NULL, NULL, NULL,'Origin Music');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (25, '2020-01-14 16:01:04', NULL, NULL, NULL, NULL,'Youtube');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (1, '2019-11-25 15:19:25', NULL, NULL, NULL, NULL, 'ASCAP');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (26, '2020-01-14 16:01:34', NULL, NULL, NULL, NULL,'Clippers');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (9, '2019-12-30 18:08:36', NULL, NULL, NULL, NULL, 'MCPS');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (13, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'PRS');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (22, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'The Orchard');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (23, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'TONO');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (24, '2020-01-13 16:01:56', NULL, NULL, NULL, NULL,'UMG');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (28, '2020-01-21 23:29:06', NULL, NULL, NULL, NULL,'GEMA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (29, '2020-01-21 23:29:19', NULL, NULL, NULL, NULL,'KODA');
INSERT INTO "Source"("Id", "CreatedOn", "ModifiedOn", "CreatedByUserLogin", "ModifiedByUserLogin", "Description", "Name") VALUES (30, '2020-01-21 23:29:39', NULL, NULL, NULL, NULL,'ACUM');
